services:
  cockroach:
    image: localhost/cockroachdb
    container_name: CockroachDB
    hostname: CockroachDB
    volumes:
      - ./cockroach/:/space/db/
    ports:
      - 8080:8080
    command: cockroach start --insecure --store=path=data,size=10GB --http-addr=0.0.0.0:8080 --listen-addr=0.0.0.0:9080 --join=localhost:9080 

  gin:
    image: localhost/gin
    container_name: gin
    hostname: gin
    volumes:
      - ./gin/:/space/work/
    ports:
      - 6060:6060
      - 8002:8002
    command: go run .

