services:
  # Production
  cockroach:
    build:
      context: ./build/cockroach/
      x-bake:
        tags:
          - localhost/cockroachdb
        platforms:
          - linux/amd64 

  caddy:
    build:
      context: ./build/caddy/
      x-bake:
        tags:
          - localhost/caddy
        platforms:
          - linux/amd64

  frontend:
    build:
      context: ./build/frontend/
      x-bake:
        tags:
          - localhost/frontend
        platforms:
          - linux/amd64

  apiserver:
    build:
      context: ./build/apiserver/
      x-bake:
        tags:
          - localhost/apiserver
        platforms:
          - linux/amd64

  # Dev
  gin:
    build:
      context: ./build/gin/
      x-bake:
        tags:
          - localhost/gin
        platforms:
          - linux/arm64
  
  svelte:
    build:
      context: ./build/svelte/
      x-bake:
        tags:
          - localhost/svelte
        platforms:
          - linux/arm64

        
# docker buildx create --use --name mybuilder 
# docker buildx bake -f docker-compose.build.yml