services:
  cockroach:
    image: anchorboard/todo-cockroachdb
    container_name: CockroachDB
    hostname: CockroachDB
    volumes:
      - ./cockroach/data/:/space/db/
    ports:
      - 28000:28000
    command: [
      "cockroach", "start", 
      "--insecure",
      "--store=path=/space/db,size=10GB",
      "--http-addr=0.0.0.0:28000",
      "--listen-addr=0.0.0.0:29000", 
      "--advertise-addr=cockroach:29000", 
      "--join=cockroach:29000"
    ]

  gin:
    image: anchorboard/todo-gin
    container_name: gin
    hostname: gin
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - MODE=dev
    volumes:
      - ./gin/:/space/work/
    ports:
      - 6060:6060
      - 8002:8002
    command: air

  svelte:
    image: anchorboard/todo-svelte
    container_name: svelte
    hostname: svelte
    volumes:
      - ./svelte/:/space/app/
    ports:
      - 8001:8001
    command: npm run dev
